// Generated by `wit-bindgen` 0.49.0. DO NOT EDIT!
#ifndef __CPP_GUEST_BINDINGS_WASM96_H
#define __CPP_GUEST_BINDINGS_WASM96_H
#include <cstdint>
#include <utility>
#include <string_view>
#include <tuple>
#include "wit.h"
namespace wasm96 {
  namespace core {
    void SetSize(uint32_t width, uint32_t height);
    void SetColor(uint8_t r, uint8_t g, uint8_t b, uint8_t a);
    void Background(uint8_t r, uint8_t g, uint8_t b);
    void Point(int32_t x, int32_t y);
    void Line(int32_t x1, int32_t y1, int32_t x2, int32_t y2);
    void Rect(int32_t x, int32_t y, uint32_t w, uint32_t h);
    void RectOutline(int32_t x, int32_t y, uint32_t w, uint32_t h);
    void Circle(int32_t x, int32_t y, uint32_t r);
    void CircleOutline(int32_t x, int32_t y, uint32_t r);
    void Image(int32_t x, int32_t y, uint32_t w, uint32_t h, std::span<uint8_t const> data);
    void ImagePng(int32_t x, int32_t y, std::span<uint8_t const> data);
    bool SvgRegister(uint64_t key, std::span<uint8_t const> data);
    void SvgDraw(uint64_t key, int32_t x, int32_t y, uint32_t w, uint32_t h);
    void SvgUnregister(uint64_t key);
    bool GifRegister(uint64_t key, std::span<uint8_t const> data);
    void GifDraw(uint64_t key, int32_t x, int32_t y);
    void GifDrawScaled(uint64_t key, int32_t x, int32_t y, uint32_t w, uint32_t h);
    void GifUnregister(uint64_t key);
    bool PngRegister(uint64_t key, std::span<uint8_t const> data);
    void PngDraw(uint64_t key, int32_t x, int32_t y);
    void PngDrawScaled(uint64_t key, int32_t x, int32_t y, uint32_t w, uint32_t h);
    void PngUnregister(uint64_t key);
    bool FontRegisterTtf(uint64_t key, std::span<uint8_t const> data);
    bool FontRegisterSpleen(uint64_t key, uint32_t size);
    void FontUnregister(uint64_t key);
    void Text(int32_t x, int32_t y, uint64_t font_key, std::string_view text);
    std::tuple<uint32_t, uint32_t> TextMeasure(uint64_t font_key, std::string_view text);
    void Triangle(int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3);
    void TriangleOutline(int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3);
    void BezierQuadratic(int32_t x1, int32_t y1, int32_t cx, int32_t cy, int32_t x2, int32_t y2, uint32_t segments);
    void BezierCubic(int32_t x1, int32_t y1, int32_t cx1, int32_t cy1, int32_t cx2, int32_t cy2, int32_t x2, int32_t y2, uint32_t segments);
    void Pill(int32_t x, int32_t y, uint32_t w, uint32_t h);
    void PillOutline(int32_t x, int32_t y, uint32_t w, uint32_t h);
    enum class Button : uint8_t {
      kB = 0,
      kY = 1,
      kSelect = 2,
      kStart = 3,
      kUp = 4,
      kDown = 5,
      kLeft = 6,
      kRight = 7,
      kA = 8,
      kX = 9,
      kL1 = 10,
      kR1 = 11,
      kL2 = 12,
      kR2 = 13,
      kL3 = 14,
      kR3 = 15,
    };

    bool IsButtonDown(uint32_t port, Button btn);
    bool IsKeyDown(uint32_t key);
    int32_t GetMouseX();
    int32_t GetMouseY();
    bool IsMouseDown(uint32_t button);
    uint32_t Init(uint32_t sample_rate);
    void PushSamples(std::span<int16_t const> samples);
    void PlayWav(std::span<uint8_t const> data);
    void PlayQoa(std::span<uint8_t const> data);
    void PlayXm(std::span<uint8_t const> data);
    void Save(std::string_view key, std::span<uint8_t const> data);
    wit::vector<uint8_t> Load(std::string_view key);
    void Log(std::string_view message);
    uint64_t Millis();
  }
}
namespace exports {
  namespace wasm96 {
    void Setup();
    void Update();
    void Draw();
  }
}

#endif
