// Generated by `wit-bindgen` 0.49.0. DO NOT EDIT!

// Ensure that the *_component_type.o object is linked in
#ifdef __wasm32__
extern "C" void __component_type_object_force_link_wasm96(void);
__attribute__((used))
void __component_type_object_force_link_wasm96_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_wasm96();
}
#endif
#include "wasm96_cpp.h"
#include <cstdlib> // realloc

extern "C" void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}


extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("set-size")))
void __wasm_import_graphicsX00set_size(int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("set-color")))
void __wasm_import_graphicsX00set_color(int32_t, int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("background")))
void __wasm_import_graphicsX00background(int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("point")))
void __wasm_import_graphicsX00point(int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("line")))
void __wasm_import_graphicsX00line(int32_t, int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("rect")))
void __wasm_import_graphicsX00rect(int32_t, int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("rect-outline")))
void __wasm_import_graphicsX00rect_outline(int32_t, int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("circle")))
void __wasm_import_graphicsX00circle(int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("circle-outline")))
void __wasm_import_graphicsX00circle_outline(int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("image")))
void __wasm_import_graphicsX00image(int32_t, int32_t, int32_t, int32_t, uint8_t *, size_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("image-png")))
void __wasm_import_graphicsX00image_png(int32_t, int32_t, uint8_t *, size_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("svg-register")))
int32_t __wasm_import_graphicsX00svg_register(int64_t, uint8_t *, size_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("svg-draw")))
void __wasm_import_graphicsX00svg_draw(int64_t, int32_t, int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("svg-unregister")))
void __wasm_import_graphicsX00svg_unregister(int64_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("gif-register")))
int32_t __wasm_import_graphicsX00gif_register(int64_t, uint8_t *, size_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("gif-draw")))
void __wasm_import_graphicsX00gif_draw(int64_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("gif-draw-scaled")))
void __wasm_import_graphicsX00gif_draw_scaled(int64_t, int32_t, int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("gif-unregister")))
void __wasm_import_graphicsX00gif_unregister(int64_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("png-register")))
int32_t __wasm_import_graphicsX00png_register(int64_t, uint8_t *, size_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("png-draw")))
void __wasm_import_graphicsX00png_draw(int64_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("png-draw-scaled")))
void __wasm_import_graphicsX00png_draw_scaled(int64_t, int32_t, int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("png-unregister")))
void __wasm_import_graphicsX00png_unregister(int64_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("font-register-ttf")))
int32_t __wasm_import_graphicsX00font_register_ttf(int64_t, uint8_t *, size_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("font-register-spleen")))
int32_t __wasm_import_graphicsX00font_register_spleen(int64_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("font-unregister")))
void __wasm_import_graphicsX00font_unregister(int64_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("text")))
void __wasm_import_graphicsX00text(int32_t, int32_t, int64_t, uint8_t *, size_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("text-measure")))
void __wasm_import_graphicsX00text_measure(int64_t, uint8_t *, size_t, uint8_t *);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("triangle")))
void __wasm_import_graphicsX00triangle(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("triangle-outline")))
void __wasm_import_graphicsX00triangle_outline(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("bezier-quadratic")))
void __wasm_import_graphicsX00bezier_quadratic(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("bezier-cubic")))
void __wasm_import_graphicsX00bezier_cubic(int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("pill")))
void __wasm_import_graphicsX00pill(int32_t, int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("graphics")))
__attribute__((import_name("pill-outline")))
void __wasm_import_graphicsX00pill_outline(int32_t, int32_t, int32_t, int32_t);
extern "C" __attribute__((import_module("input")))
__attribute__((import_name("is-button-down")))
int32_t __wasm_import_inputX00is_button_down(int32_t, int32_t);
extern "C" __attribute__((import_module("input")))
__attribute__((import_name("is-key-down")))
int32_t __wasm_import_inputX00is_key_down(int32_t);
extern "C" __attribute__((import_module("input")))
__attribute__((import_name("get-mouse-x")))
int32_t __wasm_import_inputX00get_mouse_x();
extern "C" __attribute__((import_module("input")))
__attribute__((import_name("get-mouse-y")))
int32_t __wasm_import_inputX00get_mouse_y();
extern "C" __attribute__((import_module("input")))
__attribute__((import_name("is-mouse-down")))
int32_t __wasm_import_inputX00is_mouse_down(int32_t);
extern "C" __attribute__((import_module("audio")))
__attribute__((import_name("init")))
int32_t __wasm_import_audioX00init(int32_t);
extern "C" __attribute__((import_module("audio")))
__attribute__((import_name("push-samples")))
void __wasm_import_audioX00push_samples(uint8_t *, size_t);
extern "C" __attribute__((import_module("audio")))
__attribute__((import_name("play-wav")))
void __wasm_import_audioX00play_wav(uint8_t *, size_t);
extern "C" __attribute__((import_module("audio")))
__attribute__((import_name("play-qoa")))
void __wasm_import_audioX00play_qoa(uint8_t *, size_t);
extern "C" __attribute__((import_module("audio")))
__attribute__((import_name("play-xm")))
void __wasm_import_audioX00play_xm(uint8_t *, size_t);
extern "C" __attribute__((import_module("storage")))
__attribute__((import_name("save")))
void __wasm_import_storageX00save(uint8_t *, size_t, uint8_t *, size_t);
extern "C" __attribute__((import_module("storage")))
__attribute__((import_name("load")))
void __wasm_import_storageX00load(uint8_t *, size_t, uint8_t *);
extern "C" __attribute__((import_module("system")))
__attribute__((import_name("log")))
void __wasm_import_systemX00log(uint8_t *, size_t);
extern "C" __attribute__((import_module("system")))
__attribute__((import_name("millis")))
int64_t __wasm_import_systemX00millis();
void wasm96::core::SetSize(uint32_t width, uint32_t height)
{
  __wasm_import_graphicsX00set_size((int32_t(width)), (int32_t(height)));
}
void wasm96::core::SetColor(uint8_t r, uint8_t g, uint8_t b, uint8_t a)
{
  __wasm_import_graphicsX00set_color((int32_t(r)), (int32_t(g)), (int32_t(b)), (int32_t(a)));
}
void wasm96::core::Background(uint8_t r, uint8_t g, uint8_t b)
{
  __wasm_import_graphicsX00background((int32_t(r)), (int32_t(g)), (int32_t(b)));
}
void wasm96::core::Point(int32_t x, int32_t y)
{
  __wasm_import_graphicsX00point((int32_t(x)), (int32_t(y)));
}
void wasm96::core::Line(int32_t x1, int32_t y1, int32_t x2, int32_t y2)
{
  __wasm_import_graphicsX00line((int32_t(x1)), (int32_t(y1)), (int32_t(x2)), (int32_t(y2)));
}
void wasm96::core::Rect(int32_t x, int32_t y, uint32_t w, uint32_t h)
{
  __wasm_import_graphicsX00rect((int32_t(x)), (int32_t(y)), (int32_t(w)), (int32_t(h)));
}
void wasm96::core::RectOutline(int32_t x, int32_t y, uint32_t w, uint32_t h)
{
  __wasm_import_graphicsX00rect_outline((int32_t(x)), (int32_t(y)), (int32_t(w)), (int32_t(h)));
}
void wasm96::core::Circle(int32_t x, int32_t y, uint32_t r)
{
  __wasm_import_graphicsX00circle((int32_t(x)), (int32_t(y)), (int32_t(r)));
}
void wasm96::core::CircleOutline(int32_t x, int32_t y, uint32_t r)
{
  __wasm_import_graphicsX00circle_outline((int32_t(x)), (int32_t(y)), (int32_t(r)));
}
void wasm96::core::Image(int32_t x, int32_t y, uint32_t w, uint32_t h, std::span<uint8_t const> data)
{
  auto&& vec0 = data;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  __wasm_import_graphicsX00image((int32_t(x)), (int32_t(y)), (int32_t(w)), (int32_t(h)), std::move(ptr0), std::move(len0));
}
void wasm96::core::ImagePng(int32_t x, int32_t y, std::span<uint8_t const> data)
{
  auto&& vec0 = data;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  __wasm_import_graphicsX00image_png((int32_t(x)), (int32_t(y)), std::move(ptr0), std::move(len0));
}
bool wasm96::core::SvgRegister(uint64_t key, std::span<uint8_t const> data)
{
  auto&& vec0 = data;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  auto ret = __wasm_import_graphicsX00svg_register((int64_t(key)), std::move(ptr0), std::move(len0));
  return (bool(ret));
}
void wasm96::core::SvgDraw(uint64_t key, int32_t x, int32_t y, uint32_t w, uint32_t h)
{
  __wasm_import_graphicsX00svg_draw((int64_t(key)), (int32_t(x)), (int32_t(y)), (int32_t(w)), (int32_t(h)));
}
void wasm96::core::SvgUnregister(uint64_t key)
{
  __wasm_import_graphicsX00svg_unregister((int64_t(key)));
}
bool wasm96::core::GifRegister(uint64_t key, std::span<uint8_t const> data)
{
  auto&& vec0 = data;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  auto ret = __wasm_import_graphicsX00gif_register((int64_t(key)), std::move(ptr0), std::move(len0));
  return (bool(ret));
}
void wasm96::core::GifDraw(uint64_t key, int32_t x, int32_t y)
{
  __wasm_import_graphicsX00gif_draw((int64_t(key)), (int32_t(x)), (int32_t(y)));
}
void wasm96::core::GifDrawScaled(uint64_t key, int32_t x, int32_t y, uint32_t w, uint32_t h)
{
  __wasm_import_graphicsX00gif_draw_scaled((int64_t(key)), (int32_t(x)), (int32_t(y)), (int32_t(w)), (int32_t(h)));
}
void wasm96::core::GifUnregister(uint64_t key)
{
  __wasm_import_graphicsX00gif_unregister((int64_t(key)));
}
bool wasm96::core::PngRegister(uint64_t key, std::span<uint8_t const> data)
{
  auto&& vec0 = data;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  auto ret = __wasm_import_graphicsX00png_register((int64_t(key)), std::move(ptr0), std::move(len0));
  return (bool(ret));
}
void wasm96::core::PngDraw(uint64_t key, int32_t x, int32_t y)
{
  __wasm_import_graphicsX00png_draw((int64_t(key)), (int32_t(x)), (int32_t(y)));
}
void wasm96::core::PngDrawScaled(uint64_t key, int32_t x, int32_t y, uint32_t w, uint32_t h)
{
  __wasm_import_graphicsX00png_draw_scaled((int64_t(key)), (int32_t(x)), (int32_t(y)), (int32_t(w)), (int32_t(h)));
}
void wasm96::core::PngUnregister(uint64_t key)
{
  __wasm_import_graphicsX00png_unregister((int64_t(key)));
}
bool wasm96::core::FontRegisterTtf(uint64_t key, std::span<uint8_t const> data)
{
  auto&& vec0 = data;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  auto ret = __wasm_import_graphicsX00font_register_ttf((int64_t(key)), std::move(ptr0), std::move(len0));
  return (bool(ret));
}
bool wasm96::core::FontRegisterSpleen(uint64_t key, uint32_t size)
{
  auto ret = __wasm_import_graphicsX00font_register_spleen((int64_t(key)), (int32_t(size)));
  return (bool(ret));
}
void wasm96::core::FontUnregister(uint64_t key)
{
  __wasm_import_graphicsX00font_unregister((int64_t(key)));
}
void wasm96::core::Text(int32_t x, int32_t y, uint64_t font_key, std::string_view text)
{
  auto&& vec0 = text;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  __wasm_import_graphicsX00text((int32_t(x)), (int32_t(y)), (int64_t(font_key)), std::move(ptr0), std::move(len0));
}
std::tuple<uint32_t, uint32_t> wasm96::core::TextMeasure(uint64_t font_key, std::string_view text)
{
  uint32_t ret_area[(8+sizeof(uint32_t)-1)/sizeof(uint32_t)];
  auto&& vec0 = text;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  uint8_t* ptr1 = (uint8_t*)(&ret_area);
  __wasm_import_graphicsX00text_measure((int64_t(font_key)), std::move(ptr0), std::move(len0), std::move(ptr1));
  int32_t l2 = *((int32_t const*)(ptr1 + 0));
  int32_t l3 = *((int32_t const*)(ptr1 + 4));
  auto tuple4 = std::tuple<uint32_t, uint32_t>((uint32_t(l2)), (uint32_t(l3)));
  auto result5 = std::move(tuple4);
  return result5;
}
void wasm96::core::Triangle(int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3)
{
  __wasm_import_graphicsX00triangle((int32_t(x1)), (int32_t(y1)), (int32_t(x2)), (int32_t(y2)), (int32_t(x3)), (int32_t(y3)));
}
void wasm96::core::TriangleOutline(int32_t x1, int32_t y1, int32_t x2, int32_t y2, int32_t x3, int32_t y3)
{
  __wasm_import_graphicsX00triangle_outline((int32_t(x1)), (int32_t(y1)), (int32_t(x2)), (int32_t(y2)), (int32_t(x3)), (int32_t(y3)));
}
void wasm96::core::BezierQuadratic(int32_t x1, int32_t y1, int32_t cx, int32_t cy, int32_t x2, int32_t y2, uint32_t segments)
{
  __wasm_import_graphicsX00bezier_quadratic((int32_t(x1)), (int32_t(y1)), (int32_t(cx)), (int32_t(cy)), (int32_t(x2)), (int32_t(y2)), (int32_t(segments)));
}
void wasm96::core::BezierCubic(int32_t x1, int32_t y1, int32_t cx1, int32_t cy1, int32_t cx2, int32_t cy2, int32_t x2, int32_t y2, uint32_t segments)
{
  __wasm_import_graphicsX00bezier_cubic((int32_t(x1)), (int32_t(y1)), (int32_t(cx1)), (int32_t(cy1)), (int32_t(cx2)), (int32_t(cy2)), (int32_t(x2)), (int32_t(y2)), (int32_t(segments)));
}
void wasm96::core::Pill(int32_t x, int32_t y, uint32_t w, uint32_t h)
{
  __wasm_import_graphicsX00pill((int32_t(x)), (int32_t(y)), (int32_t(w)), (int32_t(h)));
}
void wasm96::core::PillOutline(int32_t x, int32_t y, uint32_t w, uint32_t h)
{
  __wasm_import_graphicsX00pill_outline((int32_t(x)), (int32_t(y)), (int32_t(w)), (int32_t(h)));
}
bool wasm96::core::IsButtonDown(uint32_t port, Button btn)
{
  auto ret = __wasm_import_inputX00is_button_down((int32_t(port)), int32_t(btn));
  return (bool(ret));
}
bool wasm96::core::IsKeyDown(uint32_t key)
{
  auto ret = __wasm_import_inputX00is_key_down((int32_t(key)));
  return (bool(ret));
}
int32_t wasm96::core::GetMouseX()
{
  auto ret = __wasm_import_inputX00get_mouse_x();
  return (int32_t(ret));
}
int32_t wasm96::core::GetMouseY()
{
  auto ret = __wasm_import_inputX00get_mouse_y();
  return (int32_t(ret));
}
bool wasm96::core::IsMouseDown(uint32_t button)
{
  auto ret = __wasm_import_inputX00is_mouse_down((int32_t(button)));
  return (bool(ret));
}
uint32_t wasm96::core::Init(uint32_t sample_rate)
{
  auto ret = __wasm_import_audioX00init((int32_t(sample_rate)));
  return (uint32_t(ret));
}
void wasm96::core::PushSamples(std::span<int16_t const> samples)
{
  auto&& vec0 = samples;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  __wasm_import_audioX00push_samples(std::move(ptr0), std::move(len0));
}
void wasm96::core::PlayWav(std::span<uint8_t const> data)
{
  auto&& vec0 = data;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  __wasm_import_audioX00play_wav(std::move(ptr0), std::move(len0));
}
void wasm96::core::PlayQoa(std::span<uint8_t const> data)
{
  auto&& vec0 = data;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  __wasm_import_audioX00play_qoa(std::move(ptr0), std::move(len0));
}
void wasm96::core::PlayXm(std::span<uint8_t const> data)
{
  auto&& vec0 = data;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  __wasm_import_audioX00play_xm(std::move(ptr0), std::move(len0));
}
void wasm96::core::Save(std::string_view key, std::span<uint8_t const> data)
{
  auto&& vec0 = key;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  auto&& vec1 = data;
  auto ptr1 = (uint8_t*)(vec1.data());
  auto len1 = (size_t)(vec1.size());
  __wasm_import_storageX00save(std::move(ptr0), std::move(len0), std::move(ptr1), std::move(len1));
}
wit::vector<uint8_t> wasm96::core::Load(std::string_view key)
{
  uintptr_t ret_area[((2*sizeof(void*))+sizeof(uintptr_t)-1)/sizeof(uintptr_t)];
  auto&& vec0 = key;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  uint8_t* ptr1 = (uint8_t*)(&ret_area);
  __wasm_import_storageX00load(std::move(ptr0), std::move(len0), std::move(ptr1));
  auto len2 = *((size_t*) (ptr1 + sizeof(void*)));
  auto result3 = wit::vector<uint8_t>((uint8_t*)(*((uint8_t**) (ptr1 + 0))), len2);
  return result3;
}
void wasm96::core::Log(std::string_view message)
{
  auto&& vec0 = message;
  auto ptr0 = (uint8_t*)(vec0.data());
  auto len0 = (size_t)(vec0.size());
  __wasm_import_systemX00log(std::move(ptr0), std::move(len0));
}
uint64_t wasm96::core::Millis()
{
  auto ret = __wasm_import_systemX00millis();
  return (uint64_t(ret));
}
extern "C" __attribute__((__export_name__("setup")))
void __wasm_export_setup()
{
  exports::wasm96::Setup();
}
extern "C" __attribute__((__export_name__("update")))
void __wasm_export_update()
{
  exports::wasm96::Update();
}
extern "C" __attribute__((__export_name__("draw")))
void __wasm_export_draw()
{
  exports::wasm96::Draw();
}

// Component Adapters
